# Generated by Django 4.2 on 2025-04-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='max_delivery_time',
        ),
    ]
