# Generated by Django 4.2 on 2025-05-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_rename_user_type_userprofile_type_and_more'),
        ('core_app', '0003_alter_offer_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
    ]
