# Generated by Django 4.2 on 2025-05-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_rename_rating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core_app.order')),
            ],
        ),
    ]
